### PR TITLE
trigger dev dash rebuild on core update

### PR DESCRIPTION
**Pull request by lboeman**
I believe this is set up correctly, I haven't applied this configuration because I don't have access to set up a webhook on github. @alorenzo175 could you give it a quick look?

### CODE REVIEW

**Comment by lboeman** [comment]
I guess I don't have permission to apply/diff openshift config either. I didn't realize that the secrets don't are in the same namespace here, should I just the declaration here?

**Comment by alorenzo175** [comment]
Not quite sure what you are trying to say... These should all be in the development namespace, and we should probably define that in the template

**Comment by lboeman** [comment]
Wow, sorry,  not sure what happened there. I meant to say that I did not realize that the secrets are in the development namespace. Should I remove the `core-trigger-secret.yml` file from development/sfa-dash and just use the sfa-core-trigger from development/sfa-core?

**Comment by alorenzo175** [comment]
:/ though one because it does depend on it if one were recreating just the dashboard build from scratch. Maybe just symlink it from sfa-core

**Comment by lboeman** [comment]
Alright, sorry for the back and forth here. I realized this can't just be symlinked, because sfa-dash already has a `github_trigger_secret` and both secrets would end up the same.

**Comment by alorenzo175** [comment]
Then be more specific for both secrets or just leave this

**Comment by lboeman** [comment]
Alright, I added the namespace explicitly to these config files, and empty annotations to match the config in openshift. I was able to apply just the build config without issue. I didn't have access to the monitors so that's why my diff was failing previously. I think this is ready to merge.

**Pull request merged**
